version: "3.3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-db:/var/lib/postgresql/data
  backend:
    build: ./backend
    env_file:
      - ./.env
    depends_on:
      - postgres
    ports:
      - '8000:8000'
    volumes:
      - uploads:/app/uploads

volumes:
  postgres-db:
  uploads:
